const {chromium}=require('C:/Users/S.Housing/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4173/?auto');await p.waitForFunction(()=>window.__previewData()?.automation?.lastRun);
 await p.click('#wallet-eye');await p.getByRole('button',{name:'Xem báo cáo ↗'}).click();assert.equal(await p.locator('#rpt-income').innerText(),'••••••');assert(await p.locator('#report-privacy').isVisible());assert.equal(await p.locator('#monthly-report .report-card:visible').count(),0);await p.click('#wallet-eye');assert.notEqual(await p.locator('#rpt-income').innerText(),'••••••');
 const actions=[['home','.month-chip','#modal-month'],['home','.quick-action:first-child','#modal-txn'],['home','.quick-action:nth-child(2)','#modal-txn'],['home','.notebook-add','#modal-balance-note'],['home','.wallet-actions .note-link','#modal-wallet'],['report','.add-row','#modal-saving']];
 for(const [tab,selector,modal] of actions){await p.evaluate(t=>window.switchPage(t),tab);await p.locator('#page-'+tab+' '+selector).click();assert(await p.locator(modal).isVisible(),selector);await p.keyboard.press('Escape');assert(!await p.locator(modal).isVisible());}
 for(const tool of ['loanbook','interest','saving-calc','schedule','analyze']){await p.evaluate(()=>window.switchPage('report'));await p.locator('#page-report [onclick="switchPage(\'tool-'+tool+'\')"]').click();assert(await p.locator('#page-tool-'+tool).isVisible());await p.locator('#page-tool-'+tool+' .icon-btn').click();assert(await p.locator('#page-report').isVisible());}
 for(const theme of ['dark','light'])for(const width of [320,390,430]){await p.setViewportSize({width,height:844});await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const tab of ['home','paid','txn','report','settings']){await p.evaluate(t=>window.switchPage(t),tab);assert(!(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)),theme+width+tab);const tiny=await p.locator('.page.active').evaluate(root=>[...root.querySelectorAll('.icon-btn,.wc-eye,.mnav-btn,.s-del,.chk,.fin-fixed-btn,.sec-see-all')].filter(e=>e.getClientRects().length&&e.getBoundingClientRect().height<44).map(e=>e.className));assert.deepEqual(tiny,[]);}}
 await p.setViewportSize({width:390,height:844});await p.evaluate(()=>{document.documentElement.dataset.theme='dark';window.switchPage('home')});await p.screenshot({path:'artifacts/controls-home.png'});assert.deepEqual(errors,[]);console.log('PASS privacy, modal open/close, tool navigation, touch targets and mobile dark/light layouts.');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
